apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "repl-service.fullname" . }}
  labels:
    {{- include "repl-service.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/connection: upgrade
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

spec:
  ingressClassName: nginx

  tls:
    - secretName: wildcard-replit-tls
      hosts:
        - "*.replit.bemadhav.xyz"

  rules:
    - host: "output-{{ .Release.Name }}.replit.bemadhav.xyz"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "repl-service.fullname" . }}
                port:
                  name: http

    - host: "{{ .Release.Name }}.replit.bemadhav.xyz"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "repl-service.fullname" . }}
                port:
                  name: runner
