name: Runner CI

on:
  push:
    branches: [ main ]
    paths:
      - "apps/runner/**"
      - "Docker/runner/**"

jobs:
  runner:
    uses: ./.github/workflows/docker-build.yml
    with:
      context: apps/runner
      dockerfile: ../../Docker/runner/Dockerfile
      image_name: runner
      tag: latest-stable
    secrets: inherit
