name: Runner CI

on:
  push:
    branches: [ main ]
    paths:
      - "apps/runner/**"
      - "Docker/runner/**"

jobs:
  runner:
    uses: ./docker-build.yml
    with:
      context: apps/runner
      image_name: runner
    secrets: inherit
