name: Runner Image CI

on:
  push:
    branches: [ main ]
    paths:
      - "apps/runner/**"
      - "Docker/runner/**"

jobs:
  runner:
    uses: ./.github/workflows/docker-build.yml
    with:
      context: apps/runner
      image_name: runner
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
