name: Web CI

on:
  push:
    branches: [ main ]
    paths:
      - "apps/web/**"
      - "Docker/web/**"

jobs:
  runner:
    uses: ./.github/workflows/docker-build.yml
    with:
      context: apps/web
      dockerfile: ../../Docker/web/Dockerfile
      image_name: web
    secrets: inherit
